export const contentData = {
  tekst:
    '<h2>What is Lorem Ipsum?</h2><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p><ul><li><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p></li><li><p>Mauris quis dui sed neque maximus scelerisque.</p></li><li><p>Quisque dignissim est pharetra ipsum lobortis condimentum.</p></li><li><p>Proin at orci eget eros fringilla pulvinar.</p></li></ul><p></p><div data-youtube-video=""><iframe class="utrecht-youtube-video utrecht-youtube-video--html-iframe" src="https://www.youtube.com/embed/oStjjNGLluc?disablekb=1&amp;loop=false" aria-label="Word trainee bij de gemeente Utrecht!" width="640" height="480" style="aspect-ratio:1.3333333333333333" dataTitle="Word trainee bij de gemeente Utrecht!" autoplay=""></iframe><div hidden=""></div></div>',
  procedureBeschrijving:
    '<h2>Why do we use it?</h2><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p><div><div><span>DigiD</span> <a href="https://asp3.lvp.nl/amisweb/utrecht/amis3/amis.php?action=schema1">Reserveer aanhanger of bakfiets</a></div></div><div style="display:inline-grid"><h3>Meerdere Call To Action Knoppen groep 1</h3><div><h4>Inloggen met DigiD</h4><div><span>DigiD</span> <a href="https://example.com">Inloggen </a></div></div><div><h4>Zonder DigiD </h4><div><span></span> <a href="https://example.com">Inloggen</a></div></div></div>,<div style="display:inline-grid"><h3>Meerdere Call To Action Knoppen groep 2</h3><div><h4>Inloggen met eHerkening</h4><div><span>eHerkenning</span> <a href="https://example.com">Inloggen </a></div></div><div><h4>Inloggen met eDAS </h4><div><span>eIDAS</span> <a href="https://example.com">Inloggen </a></div></div></div>',
  bewijs:
    '<section><h2>Spotlightblok </h2><p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#x27;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p></section><section><h2>Spotlightblok Met Call to Action knop</h2><p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#x27;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p><div><h3>Inloggen net DigiD</h3><div><span>DigiD</span> <a href="https://example.com">Inloggen</a></div></div></section>',
  vereisten:
    '<section><h2>Uitklapmenu kop voorbeeld 1</h2><p>Uitklapmenu inhoud voorbeeld 1</p><p>Lorem Ipsum<span> is simply dummy text of the printing and typesetting industry.</span></p><p></p></section><section><h2>Uitklapmenu kop voorbeeld 2</h2><p>Uitklapmenu inhoud voorbeeld 2</p><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p></section>',
  wtdBijGeenReactie: '<a dir="rtl" lang="ar" href="https://example.com">Link Component</a>',
  bezwaarEnBeroep:
    '<h2>Image component - Contact</h2><p></p><p><img src="http://localhost:1337/uploads/alex_dudar_5k_nos_Y4v_IQ_unsplash_2dc46ad336.jpg"/></p>',
  notice:
    '<h2>Table voorbeeld met Caption</h2><p></p><figure><figcaption>Voorbeeld van demo data</figcaption><table><colgroup><col/><col/><col/></colgroup><tbody><tr><th><p>Kolom A</p></th><th><p>Kolom B</p></th><th><p>Kolom C</p></th></tr><tr><td><p>Waarde 1</p></td><td><p>Waarde 2</p></td><td><p>Waarde 3</p></td></tr><tr><td><p>Waarde 4</p></td><td><p>Waarde 5</p></td><td><p>Waarde 6</p></td></tr><tr><td><p>Waarde 7</p></td><td><p>Waarde 8</p></td><td><p>Waarde 9</p></td></tr></tbody></table></figure><p></p><h2>Table voorbeeld</h2><p></p><table><colgroup><col/><col/><col/></colgroup><tbody><tr><th><p>Kolom A</p></th><th><p>Kolom B</p></th><th><p>Kolom C</p></th></tr><tr><td><p>Waarde 1</p></td><td><p>Waarde 2</p></td><td><p>Waarde 3</p></td></tr><tr><td><p>Waarde 4</p></td><td><p>Waarde 5</p></td><td><p>Waarde 6</p></td></tr><tr><td><p>Waarde 7</p></td><td><p>Waarde 8</p></td><td><p>Waarde 9</p></td></tr></tbody></table>',
  kostenEnBetaalmethoden:
    '<h2>Kosten</h2><p><span dataStrapiCategory="price" dataStrapiIdref="7395d0a3-c3b3-4951-9fd5-1c8e654ba391">€ 10,00</span></p>',
  contact:
    '<h2>Openformulier knop</h2><div><div><span>eHerkenning</span> <a href="http://localhost:3000/form/paspoort-aanvraag">Paspoort aanvraag</a></div></div>',
  deskMemo:
    '<h2>Inleiding - Internal </h2><p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum. Perspiciatis minima nesciunt dolorem! Officiis iure rerum voluptates a cumque velit</span></p><h2>Aanvraag - internal </h2><p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum. Perspiciatis minima nesciunt dolorem! Officiis iure rerum voluptates a cumque velit</span></p><p>Kosten</p><p><span dataStrapiCategory="price" dataStrapiIdref="7395d0a3-c3b3-4951-9fd5-1c8e654ba391">€ 10,00</span></p>',
};
